[tool.poetry]
name = "utunes"
version = "0"
description = "Microscopic music library manager and music player"
authors = ["Radian LLC <contact+utunes@radian.codes>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
mutagen = "^1.47.0"
portalocker = "^3.2.0"
python-mpv = "^1.0.8"
psutil = "^7.2.2"

[tool.poetry.scripts]
utunes = 'utunes:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
